teightJan/blogs_app/urls.py
from django.urls import path
from .views import (
                    CreatePostView,
                    ListPostView,
                    ListPostViewFollowed,
                    DetailPostView,
                    UpdatePostView,
                    DeletePostView,
                    publish_post,
                    DetailPostHistoryView,
                    searchResults,
                    like_post,
                    )
from .views_comments import createComment


app_name = "blogs"

urlpatterns = [
    path('post/new/', CreatePostView.as_view(), name="new-post"),
    # path('post/new/publish', CreatePostView2.as_view(), name="new-publish-post"),
    path('', ListPostView.as_view(), name="all-post"),
    path('following/', ListPostViewFollowed.as_view(), name="all-following-post"),
    path('post/<int:pk>/', DetailPostView.as_view(), name="post"),
    path('post/<int:pk>/edit', UpdatePostView.as_view(), name="edit-post"),
    path('post/<int:pk>/delete', DeletePostView.as_view(), name="delete-post"),
    path('post/<int:pk>/comment', createComment, name="comment-post"),
    path('post/<int:pk>/publish', publish_post, name="publish-post"),
    path('post/<int:pk>/like/', like_post, name="like-post"),
    path('post/<int:pk>/history', DetailPostHistoryView.as_view(), name="history-post"),
    path('search/', searchResults, name="search-results"),
]

teightJan/system_app/urls.py
from django.urls import path
from .views import about, contact, user_login, user_logout


app_name = "system"

urlpatterns = [
    # path('', about, name="about"),
    path('about/', about, name="about"),
    path('contact/', contact, name="contact"),
    path('login/', user_login, name="login"),
    path('logout/', user_logout, name="logout"),

    # not needed as added LOGIN_URL value in the settings.py file
    # path('accounts/login/', user_login, name="account-login"),
]

teightJan/teightJan/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
# from django.contrib.auth.views import logout

# def logout_view(request):
#     logout(request)
#     # Redirect to a success page.

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('system_app.urls')),
    path('', include('blogs_app.urls')),
    path('', include('users_app.urls')),
    path('', include('social_django.urls', namespace='social')),
    # path('logout/', logout, {'next_page': settings.LOGOUT_REDIRECT_URL}, name='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    import debug_toolbar
    urlpatterns = [
        path('__debug__', include(debug_toolbar.urls))
    ] + urlpatterns

teightJan/users_app/urls.py
from django.urls import path
from .views import profile, DetailProfileView, updateProfile, profileView, create_social_profile, follow_user


app_name = "users"

urlpatterns = [
    path('profile/create/', profile, name="create-profile"),
    # path('profile/<int:pk>/', DetailProfileView.as_view(), name="view-profile"),
    path('profile/<int:pk>/', profileView, name="view-profile"),
    path('profile/edit/', updateProfile, name="edit-profile"),
    path('profile/edit/social/', create_social_profile, name="edit-social-profile"),
    path('profile/<int:pk>/follow/', follow_user, name="follow-profile"),
]

teightJan/users_app/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image


# Create your models here.
class Author_model(models.Model):
    author_name = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    git = models.URLField(max_length=128, blank=True)
    profile_pic = models.ImageField(default='default.jpeg', upload_to='profile_pics')
    # followed_by = models.ManyToManyField('self', related_name="followed_by", blank=True, null=True, default=[])

    # if have to have relationship to same model, use 'self' - in quotes
    following = models.ForeignKey('self', related_name="following-authors+", blank=True, null=True, on_delete='SET_NULL')
    following_number = models.PositiveIntegerField(default=0)
    
    # followers_number = models.PositiveIntegerField(default=0)

    def get_absolute_url(self):
        return reverse('users:view-profile', kwargs={'pk':self.pk})

    def follow_user(self, follow_author):
        if Author_model.objects.filter(author_name=follow_author) and Author_model.objects.filter(author_name=follow_author)[0].author_name != self.author_name:
            if Author_model.objects.filter(author_name=follow_author)[0] not in self.following.all():
                self.following.add(Author_model.objects.filter(author_name=follow_author)[0])
                self.following_number += 1
                self.save()
            else:
                self.following.remove(Author_model.objects.filter(author_name=follow_author)[0])
                self.following_number -= 1
                self.save()

    def __str__(self):
        return str(self.author_name)

    def save(self):
        super().save()

        img = Image.open(self.profile_pic.path)
        if img.height>300 or img.width>300:
            output_size = (300,300)
            img.thumbnail(output_size)
            img.save(self.profile_pic.path)

teightJan/users_app/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Author_model


class User_form(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    def __init__(self, *args, **kwargs):
        """
        args and kwargs are required while overriding the __init__ method
        so that later the user_form(request.POST) does not get an error for
        'TypeError: __init__() takes 1 positional argument but 2 were given'
        """
        super().__init__(*args, **kwargs)
        self.fields['first_name'].widget.attrs['placeholder'] = 'First Name'
        self.fields['first_name'].widget.attrs['class'] = 'register_form'

        self.fields['last_name'].widget.attrs['placeholder'] = 'Last Name'
        self.fields['last_name'].widget.attrs['class'] = 'register_form'

        self.fields['username'].widget.attrs['placeholder'] = 'Username'
        self.fields['username'].widget.attrs['class'] = 'register_form'

        self.fields['email'].widget.attrs['placeholder'] = 'Email address'
        self.fields['email'].widget.attrs['class'] = 'register_form'

        self.fields['password'].widget.attrs['placeholder'] = 'Enter a strong password'
        self.fields['password'].widget.attrs['class'] = 'register_form'


    class Meta():
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'password')


class Profile_form(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        """
        args and kwargs are required while overriding the __init__ method
        so that later the profile_form(request.POST) does not get an error for
        'TypeError: __init__() takes 1 positional argument but 2 were given'
        """
        super().__init__(*args, **kwargs)
        self.fields['git'].widget.attrs['placeholder'] = 'Your Github profile'
        self.fields['git'].widget.attrs['class'] = 'register_form'

        self.fields['profile_pic'].widget.attrs['class'] = 'register_form'


    class Meta():
        model = Author_model
        fields = ('git', 'profile_pic')

teightJan/users_app/views.py
from django.shortcuts import render, HttpResponse, HttpResponseRedirect, get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from .forms import User_form, Profile_form
from django.contrib.auth.decorators import login_required
from django.views.generic import DetailView, UpdateView
from .models import Author_model
from blogs_app.models import Post_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.utils import timezone


# Create your views here.
def profile(request):
    user_form = User_form()
    profile_form = Profile_form()

    if request.method == "POST":
        user_form = User_form(request.POST)
        profile_form = Profile_form(request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            # done to prevent collisions since this is the same user as the user_form above
            profile = profile_form.save(commit=False)
            profile.author_name = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            return HttpResponseRedirect(reverse('system:login'))
        else:
            print(user_form.errors, profile_form.errors)
            return HttpResponse("Invalid value(s) entered")

    if request.user.is_authenticated:
        title = 'Update your profile'
    else:
        title = 'Create a profile with us'

    context = {
        'title': title,
        'user_form': user_form,
        'profile_form': profile_form,
        }
    return render(request, 'users_app/create_profile.html', context=context)


class DetailProfileView(LoginRequiredMixin, DetailView):
    login_url = '/login/'
    redirect_field_name = 'next'
    template_name = 'users_app/profile.html'

    context_object_name = 'view_profile'
    model = Author_model

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if Author_model.objects.filter(author_name=get_object_or_404(User, id=self.kwargs['pk'])):
            profile = Author_model.objects.filter(author_name=get_object_or_404(User, id=self.kwargs['pk']))[0]
            posts_to_publish = Post_model.objects.filter(author=profile, published_on=None)
            posts_by_author = Post_model.objects.filter(author=profile, published_on__lte=timezone.now())
            context['posts_by_author'] = posts_by_author
            context['posts_to_publish'] = posts_to_publish
        else:
            context['profile'] = 'not found'
        context['title'] = profile
        return context


def profileView(request, pk):
    context = {}
    if Author_model.objects.filter(author_name=get_object_or_404(User, id=pk)):
        profile = Author_model.objects.filter(author_name=get_object_or_404(User, id=pk))[0]
        posts_to_publish = Post_model.objects.filter(author=profile, published_on=None)
        posts_by_author = Post_model.objects.filter(author=profile, published_on__lte=timezone.now())
        if Author_model.objects.filter(author_name=request.user):
            if profile in Author_model.objects.filter(author_name=request.user)[0].following.all():
                followed = True
            else:
                followed = False
        else:
            followed = False
        context['posts_by_author'] = posts_by_author
        context['posts_to_publish'] = posts_to_publish
        context['title'] = profile
        context['view_profile'] = profile
        context['followed'] = followed
        context['people_followed'] = Author_model.objects.filter(author_name=request.user)[0].following.all()
        # context['followed_by'] = Author_model.objects.filter(following=request.user).all()
        current_user = Author_model.objects.filter(author_name=request.user)[0]
        print('-----------------{}'.format(Author_model.objects.filter(following=current_user).all()))

        return render(request, 'users_app/profile.html', context=context)
    else:
        profile = User.objects.filter(username=request.user.username)[0]
        context['profile'] = profile
        return render(request, 'users_app/create_social_profile.html', context=context)



@login_required
def updateProfile(request):
    user_form = User_form()
    profile_form = Profile_form()
    display_user = User.objects.filter(username=request.user.username)[0]
    display_profile = ""
    if Author_model.objects.filter(author_name=get_object_or_404(User, username=request.user.username)):
        display_profile = Author_model.objects.filter(author_name=get_object_or_404(User, username=request.user.username))[0]

    if request.method == "POST":
        user_form = User_form(request.POST)
        profile_form = Profile_form(request.POST)

        first_name = request.POST.get('first_name')
        display_user.first_name = first_name

        last_name = request.POST.get('last_name')
        display_user.last_name = last_name

        display_user.save()

        git = request.POST.get('git')
        display_profile.git = git

        if 'profile_pic' in request.FILES:
            display_profile.profile_pic = request.FILES['profile_pic']

        display_profile.save()

        return HttpResponseRedirect(reverse('users:view-profile', kwargs={'pk': display_user.pk}))

    context = {
            'title': 'Edit Profile',
            'user_form': user_form,
            'profile_form': profile_form,
            'display_user': display_user,
            'display_profile' :display_profile,
            }

    return render(request, 'users_app/update_profile.html', context=context)


def create_social_profile(request):
    user_profile = User.objects.filter(username=request.user.username)[0]
    if request.method == "POST":
        if request.POST.get('first_name'):
            user_profile.first_name = request.POST.get('first_name')
        if request.POST.get('last_name'):
            user_profile.last_name = request.POST.get('last_name')

        user_profile.save()

        author = Author_model(
                            author_name = user_profile,
                            )

        if request.POST.get('git'):
            author.git = request.POST.get('git')

        if 'profile_pic' in request.FILES:
            author.profile_pic = request.FILES['profile_pic']

        author.save()

        return redirect('users:view-profile', pk=request.user.pk)


def follow_user(request, pk):
    author = Author_model.objects.filter(author_name=request.user)[0]
    followed_author = Author_model.objects.filter(author_name=pk)[0]
    author.follow_user(followed_author)
    return redirect('users:view-profile', pk=pk)

teightJan/users_app/templates/users_app/create_profile.html
{% extends 'system_app/base.html' %}
{% block base_body_block %}
{% load staticfiles %}
<link rel="stylesheet" href="{% static 'users_app/create_profile.css' %}">
<div class="container ">
{% if user.is_authenticated %}
<br><br>
<hr class="my-1">
<br>
  <h4>Kindly logout before creating a new profile.</h4>
  <p><a href="{% url 'system:logout' %}">Logout now</a></p>
{% else %}
  <div class="row">
    <img class="letslogo" src="{% static 'system_app/letsblog.JPG' %}" alt="Let's Blog">
  </div>
    <hr class="my-4">
    <br>
  <div class="row">
    <div class="col-md-7">
      <img class="img-fluid" src="{% static 'register.jpg' %}" alt="stock-iphone">
    </div>
    <div class="col-md-4">
      <form autocomplete="off" class="mx-auto form-group" method="post" enctype="multipart/form-data">
          {% csrf_token %}
          {{ user_form.first_name }}<br><br>
          {{ user_form.last_name }}<br><br>
          {{ user_form.username }}<br><br>
          {{ user_form.email }}<br><br>
          {{ profile_form.git }}<br><br>
          {{ profile_form.profile_pic }}<br><br>
          {{ user_form.password }}<br><br>
          <input class="register_form btn btn-primary" type="submit" name="create-profile" value="Create profile">&nbsp&nbsp
          <strong>or</strong>&nbsp&nbsp
          <a class="" href="{% url 'social:begin' 'google-oauth2' %}">
            <img src="{% static 'system_app/google.png' %}" width="25" alt="google">
          </a>
      </form>
      <hr>
      <small>Already have an account? <a href="{% url 'system:login' %}">Login now.</a></small>
    </div>
  </div>
{% endif %}
</div><br><br><br>
{% endblock %}

teightJan/users_app/templates/users_app/create_social_profile.html
{% extends 'system_app/base.html' %}
{% block base_body_block %}
{% load staticfiles %}
<link rel="stylesheet" href="{% static 'users_app/create_social_profile.css' %}">
<br><br><br>
<div class="container">
  <form class="form-group" action="{% url 'users:edit-social-profile' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <h6><span class="red">Complete your profile here.</span></h6>
    <table class="table">
      <tbody>
        <tr>
          <td>First Name</td>
          <td class="user-info"><input class="input-profile" type="text" name="first_name" value="{{ profile.first_name }}"></td>
        </tr>
        <tr>
          <td>Last Name</td>
          <td class="user-info"><input class="input-profile" type="text" name="last_name" value="{{ profile.last_name }}"></td>
        </tr>
        <tr>
          <td>Email Id</td>
          <td class="user-info"><i class="help-display-email fa fa-question-circle"></i>&nbsp<span class="input-profile email-unchanged" name="email">{{ profile.email }}</span>
          <small class="input-profile help-info-email" name="">This is the information we got from your social profile.</small></td>
        </tr>
        <tr>
          <td>Username</td>
          <td class="user-info"><i class="help-display-username fa fa-question-circle"></i>&nbsp<span class="input-profile username-unchanged" name="username">{{ profile.username }}</span>
          <small class="input-profile help-info-username" name="">This is the information we got from your social profile.</small></td>
        </tr>
        <tr>
          <td>Github Link</td>
          <td class="user-info"><input class="input-profile" type="text" name="git" value="{{ display_profile.git }}"></td>
        </tr>
        <tr>
          <td>Profile Picture</td>
          <td class="user-info">
              <img class="profile-pic" src="{{ display_profile.profile_pic.url }}" alt="">
            <br><br>
            <input type="file" accept="image/*" name="profile_pic" value="">
          </td>
        </tr>
      </tbody>
    </table>
    <hr class="my-3">
    <input type="submit" class="btn btn-primary" value="Complete profile">
  </form>
</div>
<script type="text/javascript">
  $(document).ready(function(){
    $(".help-display-email").hover(function(){
      $('.email-unchanged').css("display", "none");
      $('.help-info-email').css("display", "inline");
      });
    $(".help-display-email").mouseout(function(){
      $('.help-info-email').css("display", "none");
      $('.email-unchanged').css("display", "inline");
    });
    $(".help-display-username").hover(function(){
      $('.username-unchanged').css("display", "none");
      $('.help-info-username').css("display", "inline");
      });
    $(".help-display-username").mouseout(function(){
      $('.help-info-username').css("display", "none");
      $('.username-unchanged').css("display", "inline");
    });
  });
</script>
{% endblock %}

teightJan/users_app/templates/users_app/profile.html
{% extends 'system_app/base.html' %}
{% block base_body_block %}
{% load staticfiles %}
<link rel="stylesheet" href="{% static 'users_app/profile.css' %}">
{% if profile == 'not found' %}
<div class="container jumbotron">
  <h5>work now</h5>
</div>
{% else %}
  <div class="container jumbotron">
      <div class="row">
          <div class="col-md-10">
              <h4><span class="profile-info">{{ view_profile.author_name.username }}</span>
              {% if view_profile.author_name == user %}
              &nbsp<a class="black-href" href="{% url 'users:edit-profile' %}"><i class="fas fa-edit" style="font-size:20px"></i></a>
              {% endif %}
              </h4>
          </div>
          <div class="col-md-2">
            {% if view_profile.author_name == user %}
              <form class="form-group" action="{% url 'system:logout' %}" method="post">
                  {% csrf_token %}
                  <input type="submit" class="logout-btn btn btn-warning" value="Logout">
              </form>
            {% else %}
              {% if followed %}
                <form class="form-group" action="{% url 'users:follow-profile' pk=view_profile.author_name.pk %}" method="post">
                  {% csrf_token %}
                  <input type="submit" class="logout-btn btn btn-danger" value="Unfollow">
                </form>
              {% else %}
                <form class="form-group" action="{% url 'users:follow-profile' pk=view_profile.author_name.pk %}" method="post">
                  {% csrf_token %}
                  <input type="submit" class="logout-btn btn btn-info" value="Follow">
                </form>
              {% endif %}
            {% endif %}
          </div>
      </div>
    <hr class="my-2">
      <div class="row">
        <div class="col-md-6">
          {% if view_profile.author_name.first_name %}
            {% if view_profile.author_name.first_name %}
              <p><span class="profile-label">name: </span>&nbsp&nbsp<span class="profile-info">{{ view_profile.author_name.first_name }} {{ view_profile.author_name.last_name }}</span></p>
            {% endif %}
          {% endif %}
          <p><span class="profile-label">email address: </span>&nbsp&nbsp<span class="profile-info">{{ view_profile.author_name.email }}</span></p>
          {% if view_profile.git %}
              <p><span class="profile-label">github profile: </span>&nbsp&nbsp<span class="profile-info">{{ view_profile.git }}</p>
          {% endif %}
        </div>
        <div class="col-md-3">
          <img class="profile-pic" src="{{ view_profile.profile_pic.url }}" alt="sorry no pic found"/>
        </div>
        <div style="text-align:left;" class="col-md-3">
          {% if view_profile.author_name == user %}
            {% if people_followed %}
              People I follow ({{ people_followed|length }}): <br>
              {% for people in people_followed %}
                <a href="{% url 'users:view-profile' pk=people.pk %}">{{ people.author_name }}</a><br>
              {% endfor %}
            {% else %}
              You don't follow any one.
            {% endif %}
          {% endif %}
        </div>
      </div>
  </div>
  {% if posts_by_author %}
  <div class="container posts-author">
      {% if view_profile.author_name == user %}
        <h5 class="posts-by">Posts by you</h5>
      {% else %}
        <h5 class="posts-by">Posts by {{ view_profile.author_name }}</h5>
      {% endif %}
      <ul>
          {% for post in posts_by_author %}
          <li>
              <a class="post-link" href="{% url 'blogs:post' pk=post.pk %}">{{ post.title_original }}</a><br>
          </li>
          {% endfor %}
      </ul>
  {% endif %}
  {% if posts_to_publish %}
  <div class="container posts-author">
      {% if view_profile.author_name == user %}
        <h5 class="posts-by">Posts to publish</h5>
      <ul>
          {% for post in posts_to_publish %}
          <li>
              <a class="post-link" href="{% url 'blogs:post' pk=post.pk %}">{{ post.title_original }}</a><br>
          </li>
          {% endfor %}
      {% endif %}
      </ul>
    </div>
    {% endif %}
  </div>
  <br><br>
{% endif %}
{% endblock %}

teightJan/users_app/templates/users_app/update_profile.html
{% extends 'system_app/base.html' %}
{% block base_body_block %}
{% load staticfiles %}
<link rel="stylesheet" href="{% static 'users_app/update_profile.css' %}">
<br><br><br>
<div class="container">
  <form class="form-group" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <table class="table">
      <tbody>
        <tr>
          <td>First Name</td>
          <td><input class="input-profile" type="text" name="first_name" value="{{ display_user.first_name }}"></td>
        </tr>
        <tr>
          <td>Last Name</td>
          <td><input class="input-profile" type="text" name="last_name" value="{{ display_user.last_name }}"></td>
        </tr>
        <tr>
          <td>Github Link</td>
          <td><input class="input-profile" type="text" name="git" value="{{ display_profile.git }}"></td>
        </tr>
        <tr>
          <td>Profile Picture</td>
          <td>
              <img class="profile-pic" src="{{ display_profile.profile_pic.url }}" alt="">
            <br><br>
            <input type="file" accept="image/*" name="profile_pic" value="">
          </td>
        </tr>
      </tbody>
    </table>
    <hr class="my-3">
    <input type="submit" class="btn btn-primary" value="Update">
  </form>
</div>
{% endblock %}