teightJan/blogs_app/urls.py
from django.urls import path
from .views import (
                    CreatePostView,
                    ListPostView,
                    ListPostViewFollowed,
                    DetailPostView,
                    UpdatePostView,
                    DeletePostView,
                    publish_post,
                    DetailPostHistoryView,
                    searchResults,
                    like_post,
                    )
from .views_comments import createComment


app_name = "blogs"

urlpatterns = [
    path('post/new/', CreatePostView.as_view(), name="new-post"),
    # path('post/new/publish', CreatePostView2.as_view(), name="new-publish-post"),
    path('', ListPostView.as_view(), name="all-post"),
    path('following/', ListPostViewFollowed.as_view(), name="all-following-post"),
    path('post/<int:pk>/', DetailPostView.as_view(), name="post"),
    path('post/<int:pk>/edit', UpdatePostView.as_view(), name="edit-post"),
    path('post/<int:pk>/delete', DeletePostView.as_view(), name="delete-post"),
    path('post/<int:pk>/comment', createComment, name="comment-post"),
    path('post/<int:pk>/publish', publish_post, name="publish-post"),
    path('post/<int:pk>/like/', like_post, name="like-post"),
    path('post/<int:pk>/history', DetailPostHistoryView.as_view(), name="history-post"),
    path('search/', searchResults, name="search-results"),
]

teightJan/teightJan/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
# from django.contrib.auth.views import logout

# def logout_view(request):
#     logout(request)
#     # Redirect to a success page.

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('system_app.urls')),
    path('', include('blogs_app.urls')),
    path('', include('users_app.urls')),
    path('', include('social_django.urls', namespace='social')),
    # path('logout/', logout, {'next_page': settings.LOGOUT_REDIRECT_URL}, name='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    import debug_toolbar
    urlpatterns = [
        path('__debug__', include(debug_toolbar.urls))
    ] + urlpatterns

teightJan/users_app/urls.py
from django.urls import path
from .views import profile, DetailProfileView, updateProfile, profileView, create_social_profile, follow_user


app_name = "users"

urlpatterns = [
    path('profile/create/', profile, name="create-profile"),
    # path('profile/<int:pk>/', DetailProfileView.as_view(), name="view-profile"),
    path('profile/<int:pk>/', profileView, name="view-profile"),
    path('profile/edit/', updateProfile, name="edit-profile"),
    path('profile/edit/social/', create_social_profile, name="edit-social-profile"),
    path('profile/<int:pk>/follow/', follow_user, name="follow-profile"),
]

teightJan/blogs_app/models.py
from django.db import models
from django.urls import reverse
from users_app.models import Author_model
import datetime
from django.utils import timezone


# Create your models here.
class Post_model(models.Model):
    author = models.ForeignKey(Author_model, on_delete=models.CASCADE)
    title_original = models.CharField(max_length=200)
    # title_original means the title at the current state, that will be visible to users
    title_edited = models.CharField(max_length=200, default="")
    # title_edited means the history, the title that was saved first time while creating the blog
    body_original = models.TextField()
    body_edited = models.TextField(default="")
    created_on = models.DateTimeField(auto_now_add=True)
    created_on = models.DateTimeField(default=timezone.now())
    modified_on = models.DateTimeField(blank=True, null=True)
    published_on = models.DateTimeField(blank=True, null=True)
    likes = models.PositiveIntegerField(default=0)
    liked_by = models.ManyToManyField(Author_model, related_name="liked_by", blank=True, null=True, default=[])

    def get_absolute_url(self):
        return reverse('blogs:post', kwargs={'pk':self.pk})

    def publish(self):
        self.published_on = timezone.now()
        self.save()

    def like_post(self, liked_by_user):
        if Author_model.objects.filter(author_name=liked_by_user):
            if Author_model.objects.filter(author_name=liked_by_user)[0] not in self.liked_by.all():
                self.liked_by.add(Author_model.objects.filter(author_name=liked_by_user)[0])
                self.likes += 1
                self.save()
            else:
                self.liked_by.remove(Author_model.objects.filter(author_name=liked_by_user)[0])
                self.likes -= 1
                self.save()

    def __str__(self):
        return self.title_original


class Comment_model(models.Model):
    post = models.ForeignKey(Post_model, on_delete=models.CASCADE)
    author = models.ForeignKey(Author_model, on_delete=models.CASCADE)
    comment_text = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.comment_text

teightJan/blogs_app/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import (
                                TemplateView,
                                CreateView,
                                ListView,
                                DetailView,
                                UpdateView,
                                DeleteView,
                                TemplateView,
                                )
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Comment_model, Post_model
from users_app.models import Author_model
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from django.core.paginator import Paginator
from django.utils import timezone


# Create your views here.
class CreatePostView(LoginRequiredMixin, CreateView):
    login_url = '/login/'
    redirect_field_name = 'next'

    model = Post_model
    fields = ['title_original', 'body_original']

    def form_valid(self, form):
        username=get_object_or_404(Author_model, author_name=self.request.user)
        if Author_model.objects.filter(author_name=username):
            if Author_model.objects.filter(author_name=username)[0]:
                author = Author_model.objects.filter(author_name=username)[0]
                form.instance.author = author
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Create a new blog'
        if Author_model.objects.filter(author_name=self.request.user):
            if Author_model.objects.filter(author_name=self.request.user)[0]:
                profile_pic = Author_model.objects.filter(author_name=self.request.user)[0].profile_pic
                context['profile_pic'] = profile_pic
        return context


class ListPostView(LoginRequiredMixin, ListView):
    login_url = '/login/'
    redirect_field_name = 'next'

    model = Post_model
    fields = ['title_original', 'body_original', 'author']

    ordering = ['-published_on']
    paginate_by = 5

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Let\'s Blog'
        context['following'] = False
        return context

    def get_queryset(self):
        queryset = Post_model.objects.filter(published_on__lte=timezone.now()).order_by('-published_on')
        return queryset

class ListPostViewFollowed(LoginRequiredMixin, ListView):
    login_url = '/login/'
    redirect_field_name = 'next'

    model = Post_model
    fields = ['title_original', 'body_original', 'author']

    ordering = ['-published_on']
    paginate_by = 5

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Let\'s Blog'
        context['following'] = True
        return context

    def get_queryset(self):
        followed_authors = Author_model.objects.filter(author_name=self.request.user)[0].following.all()
        queryset = Post_model.objects.filter(published_on__lte=timezone.now(),author__in=followed_authors).order_by('-published_on')
        return queryset


class DetailPostView(LoginRequiredMixin, DetailView):
    login_url = '/login/'
    redirect_field_name = 'next'

    model = Post_model
    fields = ['title_original', 'body_original', 'created_on', 'author', 'published_on', 'title_edited', 'body_edited']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        author = Author_model.objects.filter(post_model=get_object_or_404(Post_model, id=self.kwargs['pk']))[0].author_name
        context['title'] = 'Post by ' + str(author)
        comments = Comment_model.objects.filter(post=self.kwargs['pk']).order_by('-created_on')
        this_post = post_model=get_object_or_404(Post_model, id=self.kwargs['pk'])
        likes_by_users = this_post.liked_by.all()
        print('----------{}'.format(likes_by_users))
        if Author_model.objects.filter(author_name=self.request.user)[0] in this_post.liked_by.all():
            liked_by_user = True
        else:
            liked_by_user = False
        context['comments'] = comments
        context['liked_by_user'] = liked_by_user
        if likes_by_users.count() > 0:
            context['likes_by_users'] = likes_by_users
        return context


class UpdatePostView(LoginRequiredMixin, UpdateView):
    login_url = '/login/'
    redirect_field_name = 'next'
    template_name = 'blogs_app/post_model_update.html'

    model = Post_model
    fields = ['title_original', 'body_original']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Update blog'
        profile_pic = Author_model.objects.filter(author_name=self.request.user)[0].profile_pic
        context['profile_pic'] = profile_pic
        return context

    def form_valid(self, form):
        if form.instance.published_on:
            if not form.instance.modified_on:
                form.instance.title_edited = Post_model.objects.filter(pk=self.kwargs['pk'])[0].title_original
                form.instance.title_original = str(form.instance.title_original) + "(edited)"
                form.instance.body_edited = Post_model.objects.filter(pk=self.kwargs['pk'])[0].body_original
            form.instance.modified_on = timezone.now()
        return super().form_valid(form)


class DeletePostView(LoginRequiredMixin, DeleteView):
    login_url = '/login/'
    redirect_field_name = 'name'

    model = Post_model
    success_url = reverse_lazy('blogs:all-post')


def publish_post(request, pk):
    post = get_object_or_404(Post_model, pk=pk)
    post.publish()
    return redirect('blogs:post', pk=pk)


class DetailPostHistoryView(LoginRequiredMixin, DetailView):
    login_url = '/login/'
    redirect_field_name = 'next'

    model = Post_model
    template_name = 'blogs_app/post_history.html'
    fields = ['title_original', 'body_original', 'created_on', 'author', 'published_on', 'title_edited', 'body_edited', 'likes']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        author = Author_model.objects.filter(post_model=get_object_or_404(Post_model, id=self.kwargs['pk']))[0].author_name
        context['title'] = 'Post by ' + str(author)
        profile_pic = Author_model.objects.filter(author_name=self.request.user)[0].profile_pic
        context['profile_pic'] = profile_pic
        comments = Comment_model.objects.filter(post=self.kwargs['pk']).order_by('-created_on')
        context['comments'] = comments
        return context


def searchResults(request):
    search_query = ""
    authors = ""
    authors_f_name = ""
    authors_l_name = ""
    authors_git = ""
    posts_title = ""
    posts_body = ""

    if request.method == "POST":
        if request.POST.get('search-query'):
            search_query = request.POST.get('search-query')
            if search_query:
                authors_f_name = Author_model.objects.filter(author_name__first_name__icontains=search_query)
                authors_l_name = Author_model.objects.filter(author_name__last_name__icontains=search_query)
                authors = Author_model.objects.filter(author_name__username__icontains=search_query)
                authors_git = Author_model.objects.filter(git__icontains=search_query)

                posts_title = Post_model.objects.filter(title_original__icontains=search_query, published_on__lte=timezone.now())
                posts_body = Post_model.objects.filter(body_original__icontains=search_query, published_on__lte=timezone.now())
    context = {
            'title': 'Search results for '+search_query ,
            'search_query': search_query,
            'authors': authors,
            'authors_git': authors_git,
            'posts_title': posts_title,
            'posts_body': posts_body,
            'authors_f_name': authors_f_name,
            'authors_l_name': authors_l_name,
            }
    return render(request, 'blogs_app/search_results.html', context=context)


def like_post(request, pk):
    post = get_object_or_404(Post_model, pk=pk)
    liked_by_user = request.user
    post.like_post(liked_by_user)
    return redirect('blogs:post', pk=pk)

teightJan/blogs_app/templates/blogs_app/post_history.html
{% extends 'system_app/base.html' %}
{% block base_body_block %}
{% load staticfiles %}
<link rel="stylesheet" href="{% static 'blogs_app/post_history.css' %}">
<br><br>
<div class="container post-complete">
  <div class="row">
    <div class="col-md-6">
      <p class="underline">Title originally</p> <span class="post-title">{{ post_model.title_edited }}</span><hr>
      <p class="underline">Post originally</p> <span class="">{{ post_model.body_edited }}</span>
    </div>
    <div class="col-md-6">
      <p class="underline">Title as of today</p> <span class="post-title">{{ post_model.title_original }}</span><hr>
      <p class="underline">Post as of today</p> <span class="">{{ post_model.body_original }}</span>
    </div>
  </div>
</div>
<br><br>
<br><br>
{% endblock %}

teightJan/blogs_app/templates/blogs_app/post_model_detail.html
{% extends 'system_app/base.html' %}
{% block base_body_block %}
{% load staticfiles %}
<link rel="stylesheet" href="{% static 'blogs_app/post_model_detail.css' %}">
<br><br>
<div class="container post-complete">
{% if not post_model.published_on and post_model.author.author_name == user %}
  <div class="row ">
    <div class="col-md-8">
        <span class="post-title">{{ post_model.title_original }}</span>
        {% if post_model.author.author_name == user %}
          <select class="edit-post" onchange="location = this.value;">
            <option value=""></option>
            <option value="{% url 'blogs:edit-post' pk=post_model.pk %}">Edit Post&nbsp</option>
            <option value="{% url 'blogs:delete-post' pk=post_model.pk %}">Delete</option>
          </select>
        {% else %}
        {% endif %}
        <br>
        <small>Created on : {{ post_model.created_on }}</small>
    </div>
    <div class="col-md-4">
        <span class="author-name">
            <a class="black-href" href="{% url 'users:view-profile' pk=post_model.author.pk %}">
                <small>
                    {{ post_model.author|title}}
                </small>
                <img class="profile-pic" src="{{ post_model.author.profile_pic.url }}" alt="no image found">
            </a>
        </span>
    </div>
    </div><br>
    <p><span class="postarea">{{ post_model.body_original|linebreaks }}</span></p>
    {% if post_model.published_on %}
      <input id="comments-btn" onclick="display_comments()" type="submit" class="btn btn-primary btn-sm" value="Comment">
  </div>
    <div id="comments-all" class="container">
      <form class="comment-form form-group" action="{% url 'blogs:comment-post' pk=post_model.pk %}" method="POST">
        {% csrf_token %}
        <div class="row">
          <div class="col-md-10">
            <input type="text" name="comment-bar" class="comment-bar" placeholder="Add new comment">
          </div>
          <div class="col-md-2">
            <input type="submit" class="btn btn-primary btn-sm" value="Comment">
          </div>
        </div>
      </form>
    </div>
    <div class="comments-list container">
      {% for comment in comments %}
      <hr class="my-2">
      <div class="row">
        <div class="col-md-2">
          <a class="black-href" href="{% url 'users:view-profile' pk=comment.author.pk %}">
            <img class="comment-profile-pic" src="{{ comment.author.profile_pic.url }}" alt="No image found">
            <small class="comment-author">{{ comment.author }}</small><br>
          </a>
          <small class="comment-time">{{ comment.created_on }}</small>
        </div>
        <div class="col-md-10">
          <span class="font-comment">{{ comment.comment_text }}</span>
        </div>
      </div>
      <br>
      {% endfor %}
      <br>
  {% else %}
    <a class="btn btn-info" href="{% url 'blogs:publish-post' pk=post_model.pk %}">Publish</a>
  {% endif %}
  {% elif post_model.published_on %}
  <div class="row ">
    <div class="col-md-8">
        <span class="post-title">{{ post_model.title_original }}</span>
        {% if post_model.author.author_name == user %}
          <select class="edit-post" onchange="location = this.value;">
            <option value=""></option>
            {% if post_model.modified_on %}
              <option value="{% url 'blogs:history-post' pk=post_model.pk %}">View original version&nbsp</option>
            {% endif %}
            <option value="{% url 'blogs:edit-post' pk=post_model.pk %}">Edit Post&nbsp</option>
            <option value="{% url 'blogs:delete-post' pk=post_model.pk %}">Delete</option>
          </select>
        {% else %}
          {% if post_model.modified_on %}
          <select class="edit-post" onchange="location = this.value;">
            <option value=""></option>
              <option value="{% url 'blogs:history-post' pk=post_model.pk %}">View original version&nbsp</option>
          </select>
          {% endif %}
        {% endif %}
        <br>
        <small>{{ post_model.published_on }}</small>
    </div>
    <div class="col-md-4">
        <span class="author-name">
            <a class="black-href" href="{% url 'users:view-profile' pk=post_model.author.pk %}">
                <small>
                    {{ post_model.author|title}}
                </small>
                <img class="profile-pic" src="{{ post_model.author.profile_pic.url }}" alt="no image found">
            </a>
        </span>
    </div>
    </div><br>
    <p><span class="postarea">{{ post_model.body_original|linebreaks }}</span></p>
    {% if post_model.published_on %}
    <small>{{ comments|length }} comment(s)</small>&nbsp
    <a class="black-href" href="#"><small class="show-likes">{{ post_model.likes }} likes</small></a>
    <div class="liked-by">
      {% if likes_by_users %}
      <hr>
      <small>Liked by: </small>
      {% for likes_by_user in likes_by_users %}
      <a href="{% url 'users:view-profile' pk=likes_by_user.author_name.pk %}">
        <small>{{ likes_by_user.author_name }}</small>
      </a>|
      {% endfor %}
      <hr>
      {% endif %}
    </div>
    <br>
    <br>
    <div class="row">
        <div class="col-md-1">
          {% if liked_by_user == False %}
            <a id="like" class="black-href" href="{% url 'blogs:like-post' pk=post_model.pk %}"><i class="ml-3 like-btn fa-2x far fa-heart"></i></a>
          {% else %}
            <a id="liked" class="black-href" href="{% url 'blogs:like-post' pk=post_model.pk %}"><i class="ml-3 like-btn fa-2x fas fa-heart"></i></a>
          {% endif %}
        </div>
        <div class="col-md-2">
            <input id="comments-btn" onclick="display_comments()" type="submit" class="mb-3 btn btn-primary btn-sm" value="Comment">
        </div>
    </div>
      </div>
        <div id="comments-all" class="container">
          <form class="comment-form form-group" action="{% url 'blogs:comment-post' pk=post_model.pk %}" method="POST">
            {% csrf_token %}
            <div class="row">
              <div class="col-md-10">
                <input type="text" name="comment-bar" class="comment-bar" placeholder="Add new comment">
              </div>
              <div class="col-md-2">
                <input type="submit" class="btn btn-primary btn-sm" value="Comment">
              </div>
            </div>
          </form>
        </div>
        <div class="comments-list container">
          {% for comment in comments %}
          <hr class="my-2">
          <div class="row">
            <div class="col-md-2">
              <a class="black-href" href="{% url 'users:view-profile' pk=comment.author.pk %}">
                <img class="comment-profile-pic" src="{{ comment.author.profile_pic.url }}" alt="No image found">
                <small class="comment-author">{{ comment.author }}</small><br>
              </a>
              <small class="comment-time">{{ comment.created_on }}</small>
            </div>
            <div class="col-md-10">
              <span class="font-comment">{{ comment.comment_text }}</span>
            </div>
          </div>
          <br>
          {% endfor %}
          <br>
      {% else %}
        <a class="btn btn-info" href="{% url 'blogs:publish-post' pk=post_model.pk %}">Publish</a>
      {% endif %}
      {% else %}
        <h5>Post you're trying to view isn't published yet.</h5>
      {% endif %}
    </div>
<br><br>
<script type="text/javascript">
    $(document).ready(function(){
        // $("#liked").mouseover(function(){
        //     $('#unlike').css("display", "inline");
        //     $('#liked').css("display", "none");
        //     });
        // $("#liked").mouseout(function(){
        //     $('#unlike').css("display", "none");
        //     $('#liked').css("display", "inline");
        // });
        $(".show-likes").click(function(){
            $('.liked-by').toggle();
        });
        // $("#liked").click(function(){
        //     $('#liked').css("display", "none");
        //     $('#like').css("display", "inline");
        // });
    });
  if ({{ comments|length }}) {
      document.getElementById('comments-all').style.display = "none";
      document.getElementById('comments-btn').style.display = "block  ";
  }
  else {
    document.getElementById('comments-all').style.display = "none";
  }
  // function to show the comment bar if there was no previous comment
  function display_comments() {
    document.getElementById('comments-all').style.display = "block";
    document.getElementById('comments-btn').style.display = "none";
  }

</script>
{% endblock %}

teightJan/blogs_app/templates/blogs_app/post_model_form.html
{% extends 'system_app/base.html' %}
{% block base_body_block %}
{% load staticfiles %}
<link rel="stylesheet" href="{% static 'blogs_app/post_model_form.css' %}">
<br><br>
<!-- <hr class="my-0"> -->
<br>
<div class="container post-complete">
  <form class="form-group" method="post">
    {% csrf_token %}
    <div class="row">
      <div class="col-md-9">
        <p><span class="">Title: </span></p>
        <span class="post-title">{{ form.title_original }}</span><br><br>
      </div>
      <div class="col-md-3">
        <div class="profile">
            <a class="black-href" href="{% url 'users:view-profile' pk=user.pk %}"><img class="profile-pic" src="{{ profile_pic.url }}" alt="No pic found">
            {{ user.get_username }}</a>
        </div>
      </div>
    </div>
      <p><span class="postarea">Post: </span></p>
      <p><span class="postarea">{{ form.body_original }}</span></p>

      <input type="submit" class="btn btn-primary" value="Create">
    </form>
  </div>
<br><br>
{% endblock %}

teightJan/blogs_app/templates/blogs_app/post_model_list.html
{% extends 'system_app/base.html' %}
{% block base_body_block %}
{% load staticfiles %}
<link rel="stylesheet" href="{% static 'blogs_app/post_model_list.css' %}">
<br><br>
<div class="container">
    <div class="search-bar">
        <form class="form-group" action="{% url 'blogs:search-results' %}" method="POST">
            {% csrf_token %}
            <input type="text" name="search-query" class="find-post" placeholder="search">
            <input type="submit" class="search-button btn btn-info" value="Search">
        </form>
    </div>
  <div class="filter-posts">
    Filter:
    {% if following %}
      <select class="edit-post" onchange="location = this.value;">
        <option value="{% url 'blogs:all-following-post' %}">People I follow</option>
        <option value="{% url 'blogs:all-post' %}">All posts</option>
      </select>
    {% else %}
      <select class="edit-post" onchange="location = this.value;">
        <option value="{% url 'blogs:all-post' %}">All posts</option>
        <option value="{% url 'blogs:all-following-post' %}">People I follow</option>
      </select>
    {% endif %}
  </div><br>
  {% for post in post_model_list %}
    <div class="post-complete">
      <br>
      <div class="row ">
          <div class="col-md-8">
              <span class="post-title"><a class="black-href" href="{% url 'blogs:post' pk=post.pk %}">{{ post.title_original }}</a></span>
              <br>
              <small>{{ post.created_on }}</small>
          </div>
          <div class="col-md-4">
              <span class="author-name">
                  <a class="black-href" href="{% url 'users:view-profile' pk=post.author.pk %}">
                      <small>
                          {{ post.author|title }}
                      </small>
                      <img class="profile-pic" src="{{ post.author.profile_pic.url }}" alt="no image found">
                  </a>
              </span>
          </div>
          </div><br>
          <p><span class="postarea">{{ post.body_original|truncatechars:700|linebreaks }}</span>
          {% if post.body_original|length|get_digit:"-1" > 600 %}
            <small><a href="{% url 'blogs:post' pk=post.pk %}">see complete post</a></small>
          {% endif %}
          </p>
    </div><br>
  {% endfor %}
  {% if is_paginated %}
    <nav>
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}" tabindex="-1">Previous</a>
                </li>
            {% endif %}
            {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
                </li>
            {% endif %}
        </ul>
    </nav>
  {% endif %}
  <br><br>
</div>
{% endblock %}

teightJan/blogs_app/templates/blogs_app/post_model_update.html
{% extends 'system_app/base.html' %}
{% block base_body_block %}
{% load staticfiles %}
<link rel="stylesheet" href="{% static 'blogs_app/post_model_update.css' %}">
<br><br>
<hr class="my-1">
<br>
<div class="container post-complete">
  {% if post_model.author.author_name == user %}
  <form class="form-group"  method="post">
    {% csrf_token %}
    <div class="row">
      <div class="col-md-9">
        <p><span class="">Title: </span></p>
        <span class="post-title">{{ form.title_original }}</span><br><br>
      </div>
      <div class="col-md-3">
        <div class="profile">
            <a class="black-href" href="{% url 'users:view-profile' pk=user.pk %}"><img class="profile-pic" src="{{ profile_pic.url }}" alt="No pic found">
            {{ user.get_username }}</a>
        </div>
      </div>
    </div>
      <p><span class="postarea">Post: </span></p>
      <p><span class="postarea">{{ form.body_original }}</span></p>
      <input type="submit" class="btn btn-primary" value="Update">
    </form>
    {% else %}
      <h2>Users can only edit their own posts.</h2>
    {% endif %}
  </div>
</div>
{% endblock %}

teightJan/blogs_app/templates/blogs_app/search_results.html
{% extends 'system_app/base.html' %}
{% block base_body_block %}
{% load staticfiles %}
<link rel="stylesheet" href="{% static 'blogs_app/search_results.css' %}">
<br><br>
<div class="container">
  <div class="search-bar">
      <form class="form-group" action="{% url 'blogs:search-results' %}" method="POST">
          {% csrf_token %}
          <input type="text" name="search-query" class="find-post" value="{{ search_query }}" placeholder="search">
          <input type="submit" class="search-button btn btn-info" value="Search">
      </form>
  </div>
  {% if search_query %}
  <h6>Search results for "{{ search_query }}"</h6>
  {% endif %}

  {% if authors %}
  <div class="post-complete">
    <strong>Authors usernames:</strong>
    <ul>
      {% for author in authors %}
      <li>
        <a href="{% url 'users:view-profile' pk=author.author_name.pk %}">{{ author }}</a>
      </li>
      {% endfor %}
    </ul>
  </div><br>
  {% endif %}

  {% if authors_f_name %}
  <div class="post-complete">
    <strong>Authors' first names:</strong>
    <ul>
      {% for author_f_name in authors_f_name %}
      <li>
        <a href="{% url 'users:view-profile' pk=author_f_name.author_name.pk %}">
          <span class="title-underline">{{ author_f_name.author_name.first_name }} ({{ author_f_name.author_name }})</span><br>
          <p>
            {{ author_f_name.firstname }}
          </p>
        </a>
      </li><hr>
      {% endfor %}
    </ul>
  </div><br>
  {% endif %}

  {% if authors_l_name %}
  <div class="post-complete">
    <strong>Authors' last names:</strong>
    <ul>
      {% for author_l_name in authors_l_name %}
      <li>
        <a href="{% url 'users:view-profile' pk=author_l_name.author_name.pk %}">
          <span class="title-underline">{{ author_l_name.author_name.last_name }} ({{ author_l_name.author_name }})</span><br>
          <p>
            {{ author_l_name.lastname }}
          </p>
        </a>
      </li><hr>
      {% endfor %}
    </ul>
  </div><br>
  {% endif %}

  {% if authors_git %}
  <div class="post-complete">
    <strong>Git profiles of authors:</strong>
    <ul>
      {% for author_git in authors_git %}
      <li>
        <a href="{% url 'users:view-profile' pk=author_git.author_name.pk %}">{{ author_git.git }}</a>
      </li>
      {% endfor %}
    </ul>
  </div><br>
  {% endif %}

  {% if posts_title %}
  <div class="post-complete">
    <strong>Post titles:</strong>
    <ul>
      {% for post_title in posts_title %}
      <li>
        <a href="{% url 'blogs:post' pk=post_title.pk %}">{{ post_title }}</a>
      </li>
      {% endfor %}
    </ul>
  </div><br>
  {% endif %}

  {% if posts_body %}
  <div class="post-complete">
    <strong>Post bodies:</strong>
    <ul>
      {% for post_body in posts_body %}
      <li>
        <a href="{% url 'blogs:post' pk=post_body.pk %}"><span class="title-underline">{{ post_body }}</span><br>
        <p>{{ post_body.body_original|truncatechars:200 }}</p></a>
      </li><hr>
      {% endfor %}
    </ul>
  </div><br>
  {% endif %}

  <br><br>
</div>
{% endblock %}