teightJan/blogs_app/urls.py
from django.urls import path
from .views import (
                    CreatePostView,
                    ListPostView,
                    ListPostViewFollowed,
                    DetailPostView,
                    UpdatePostView,
                    DeletePostView,
                    publish_post,
                    DetailPostHistoryView,
                    searchResults,
                    like_post,
                    )
from .views_comments import createComment


app_name = "blogs"

urlpatterns = [
    path('post/new/', CreatePostView.as_view(), name="new-post"),
    # path('post/new/publish', CreatePostView2.as_view(), name="new-publish-post"),
    path('', ListPostView.as_view(), name="all-post"),
    path('following/', ListPostViewFollowed.as_view(), name="all-following-post"),
    path('post/<int:pk>/', DetailPostView.as_view(), name="post"),
    path('post/<int:pk>/edit', UpdatePostView.as_view(), name="edit-post"),
    path('post/<int:pk>/delete', DeletePostView.as_view(), name="delete-post"),
    path('post/<int:pk>/comment', createComment, name="comment-post"),
    path('post/<int:pk>/publish', publish_post, name="publish-post"),
    path('post/<int:pk>/like/', like_post, name="like-post"),
    path('post/<int:pk>/history', DetailPostHistoryView.as_view(), name="history-post"),
    path('search/', searchResults, name="search-results"),
]

teightJan/system_app/urls.py
from django.urls import path
from .views import about, contact, user_login, user_logout


app_name = "system"

urlpatterns = [
    # path('', about, name="about"),
    path('about/', about, name="about"),
    path('contact/', contact, name="contact"),
    path('login/', user_login, name="login"),
    path('logout/', user_logout, name="logout"),

    # not needed as added LOGIN_URL value in the settings.py file
    # path('accounts/login/', user_login, name="account-login"),
]

teightJan/teightJan/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
# from django.contrib.auth.views import logout

# def logout_view(request):
#     logout(request)
#     # Redirect to a success page.

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('system_app.urls')),
    path('', include('blogs_app.urls')),
    path('', include('users_app.urls')),
    path('', include('social_django.urls', namespace='social')),
    # path('logout/', logout, {'next_page': settings.LOGOUT_REDIRECT_URL}, name='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    import debug_toolbar
    urlpatterns = [
        path('__debug__', include(debug_toolbar.urls))
    ] + urlpatterns

teightJan/users_app/urls.py
from django.urls import path
from .views import profile, DetailProfileView, updateProfile, profileView, create_social_profile, follow_user


app_name = "users"

urlpatterns = [
    path('profile/create/', profile, name="create-profile"),
    # path('profile/<int:pk>/', DetailProfileView.as_view(), name="view-profile"),
    path('profile/<int:pk>/', profileView, name="view-profile"),
    path('profile/edit/', updateProfile, name="edit-profile"),
    path('profile/edit/social/', create_social_profile, name="edit-social-profile"),
    path('profile/<int:pk>/follow/', follow_user, name="follow-profile"),
]

teightJan/system_app/models.py
from django.db import models

# Create your models here.

teightJan/system_app/views.py
from django.shortcuts import render, HttpResponseRedirect, HttpResponse, redirect
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse
from django.contrib.auth.decorators import login_required
import time


# Create your views here.
@login_required
def about(request):
    return render(request, 'system_app/about.html', context={'title': 'About'})


def user_login(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)
        # print('Printing now - {}'.format(type(request.user)))
        if user:
            if user.is_active:
                login(request, user)
                # return HttpResponseRedirect(reverse('users:view-profile', kwargs={'pk':user.pk}))
                return HttpResponseRedirect(reverse('blogs:all-post'))
            else:
                # return HttpResponse("<h2>This user is not active</h2>")
                return redirect('system_app/login_failed.html', context={'title':'Login', 'data':'inactive'})
        else:
            # return HttpResponse("<h2>Invalid username/password</h2>")
            return render(request, 'system_app/login_failed.html', context={'title':'Login', 'data':'incorrect'})

    return render(request, 'system_app/login.html', context={'title': 'Login'})


@login_required
def user_logout(request):
    logout(request)
    # time.sleep(1)
    # return HttpResponseRedirect(reverse('system:login'))
    return render(request, 'system_app/logout.html', context={'title': 'Logout'})


@login_required
def contact(request):
    return render(request, 'system_app/contact.html', context={'title': 'Contact'})

teightJan/system_app/templates/system_app/about.html
{% extends 'system_app/base.html' %}
{% block base_body_block %}
{% load staticfiles %}
<link rel="stylesheet" href="{% static 'system_app/about.css' %}">
<br><br>
  <div class="container container-class">
    <br>
    <h2>About Let's Blog</h2>
    <hr class="my-3">
    <p>This is a little blogging app where users can create account and login, post blogs, comment on other' blogs.</p>
    <p>We have tonnes of features planned for the future. Keep visiting! :)</p>
    <br><br>
  </div>
{% endblock %}

teightJan/system_app/templates/system_app/base.html
<!DOCTYPE html>
{% load staticfiles %}
<link rel="stylesheet" href="{% static 'system_app/base.css' %}">
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"> -->
    <!-- <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet"> -->
    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css"> -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Fredoka+One" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Expletus+Sans|Krona+One" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
    <title>{{ title }}</title>
  </head>
  <body>
    <div class="wrapper">
      {% if user.is_authenticated %}
      <nav class="fixed-top  navbar navbar-expand-lg navbar-light">
          <div class="nav-container">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbar-collapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse">
              <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                  <a id="nav-link" class="nav-link m-auto" href="{% url 'blogs:new-post' %}">Create blog</a>
                </li>
                <a id="center-nav-link" class="navbar-brand" href="{% url 'blogs:all-post' %}"><img class="letslogo" src="{% static 'system_app/letsblog.JPG' %}" alt="Let's Blog"></a>
              </ul>
              <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                  <a id="nav-link" class="nav-link" href="{% url 'system:about' %}">About </a>
                </li>
                <li class="nav-item">
                  <a id="nav-link" class="nav-link" href="{% url 'system:contact' %}">Contact Us </a>
                </li>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" role="button" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    More
                  </a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'users:view-profile' pk=user.pk %}">{{ user.get_username|title }}</a>
                    <a class="dropdown-item" href="{% url 'system:logout' %}">Logout</a>
                    <a target="_blank" class="dropdown-item" href="{% url 'admin:index' %}">Admin</a>
                  </div>
                </li>
              </ul>
            </div>
        </div>
      </nav>
      {% else %}
        <a href="{% url 'system:login' %}"></a>
      {% endif %}
      <br>
      {% block base_body_block %}
        <!-- things come here from the pages that inherit this base page -->
      {% endblock %}
    </body>
    <footer>
      <div class="container">
        <div class="mt-3 row">
          <div class="col-md-6">
            <a class="black-href" target="_blank" href="https://github.com/okaysidd/Blog-app">Read the code on Github <i class="fab fa-github"></i></a>
          </div>
          <div class="col-md-6">
            <a class="black-href" target="_blank" href="{% url 'admin:index' %}">Admin</a>
          </div>
        </div>
      </div>
    </footer>
  </div>
</html>

teightJan/system_app/templates/system_app/contact.html
{% extends 'system_app/base.html' %}
{% block base_body_block %}
{% load staticfiles %}
<link rel="stylesheet" href="{% static 'system_app/about.css' %}">
<br><br>
  <div class="container container-class">
    <br>
    <h2>Contact Us</h2>
    <hr class="my-3">
    <p>Email address : <a href="mailto:siddhartha.sehgal94@gmail.com?subject=Just popped to say Hi">siddhartha.sehgal94@gmail.com</a></p>
    <p>Github link : <a target="_blank" href="https://www.github.com/okaysidd">@okaysidd</a></p>
    <p>Twitter : <a href="https://www.twitter.com/okaysidd">@okaysidd</a></p>
    <br><br>
  </div>
{% endblock %}

teightJan/system_app/templates/system_app/login.html
{% extends 'system_app/base.html' %}
{% block base_body_block %}
{% load staticfiles %}
<link rel="stylesheet" href="{% static 'system_app/login.css' %}">
<div class="container">
{% if user.is_authenticated %}
<br><br>
<hr class="my-1">
<br>
  <h4>Kindly logout before logging in again.</h4>
  <p><a href="{% url 'system:logout' %}">Logout now</a></p>
{% else %}
<div class="row">
  <img class="letslogo" src="{% static 'system_app/letsblog.JPG' %}" alt="Let's Blog">
</div>
  <hr class="my-4">
  <br>
    <div class="row">
      <div class="col-md-7">
        <img class="img-fluid" src="{% static 'system_app/login.png' %}" alt="stock-iphone">
      </div>
      <div class="col-md-4">

        <form class="login-form form-group" action="" method="post">
          {% csrf_token %}
          <legend><small>Username and password</small></legend>
          <p><input type="text" name="username" placeholder="enter username"></p>
          <p><input type="password" name="password" placeholder="enter password"></p>
          <input class="btn btn-primary" type="submit" name="submit" value="Login">&nbsp&nbsp <strong>or</strong>&nbsp&nbsp
          <a class="" href="{% url 'social:begin' 'google-oauth2' %}">
            <img src="{% static 'system_app/google.png' %}" width="25" alt="google"></a>
          <br>
        </form>
        <hr>

      <small>Don't have an account? No worries!</small><br>
      <small><a href="{% url 'users:create-profile' %}">Create now in under a minute.</a></small>
      </div>
    </div>
  </div>
{% endif %}
<br><br>
{% endblock %}

teightJan/system_app/templates/system_app/login_failed.html
{% extends 'system_app/base.html' %}
{% block base_body_block %}
{% load staticfiles %}
<link rel="stylesheet" href="{% static 'system_app/login.css' %}">
<div class="container ">
{% if user.is_authenticated %}
<br><br>
<hr class="my-1">
<br>
  <h4>Kindly logout before logging in again.</h4>
  <p><a href="{% url 'system:logout' %}">Logout now</a></p>
{% else %}
<div class="row">
  <img class="letslogo" src="{% static 'system_app/letsblog.JPG' %}" alt="Let's Blog">
</div>
  <hr class="my-4">
  <br>
    <div class="row">
      <div class="col-md-7">
        <img class="img-fluid" src="{% static 'system_app/login.png' %}" alt="stock-iphone">
      </div>
      <div class="mt-5 col-md-4">
        {% if data == 'incorrect' %}
          <p>User not found, or incorrect credentials entered. <a href="{% url 'system:login' %}">Try again?</a></p>
        {% elif data == 'inactive' %}
          <p>This user is not activated. <a href="{% url 'system:login' %}">Try with another account?</a></p>
        {% endif %}
      </div>
    </div>
  </div>
{% endif %}
<br><br>
{% endblock %}

teightJan/system_app/templates/system_app/logout.html
{% extends 'system_app/base.html' %}
{% block base_body_block %}
{% load staticfiles %}
  <div class="container jumbotron">
    Successfully logged out.
    <br>
    <a href="{% url 'system:login' %}">Log in again</a>
  </div>
{% endblock %}